package com.pingfit.dao;

import com.pingfit.dao.hibernate.BasePersistentClass;
import com.pingfit.dao.hibernate.HibernateUtil;
import org.apache.log4j.Logger;

import java.util.Iterator;

/**
 * Userrole generated by hbm2java
 */

public class Systemprop extends BasePersistentClass implements java.io.Serializable {


    // Fields

     private int systempropid;
     private String name;
     private String value;


    public static Systemprop get(Integer id) {
        Logger logger = Logger.getLogger("com.pingfit.dao.Systemprop");
        try {
            logger.debug("Systemprop.get(" + id + ") called.");
            Systemprop obj = (Systemprop) HibernateUtil.getSession().get(Systemprop.class, id);
            if (obj == null) {
                logger.debug("Systemprop.get(" + id + ") returning new instance because hibernate returned null.");
                return new Systemprop();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.pingfit.dao.Systemprop", ex);
            return new Systemprop();
        }
    }

    // Constructors

    /** default constructor */
    public Systemprop() {
    }


    public int getSystempropid() {
        return systempropid;
    }

    public void setSystempropid(int systempropid) {
        this.systempropid = systempropid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
